oauth2_frontend_authorization_login:
    pattern: ^/oauth2-token/login$
    provider: commerce_customer_user
    context: customer_identity
oauth2_frontend_authorization_authenticate:
    pattern: ^/oauth2-token/(authorize|login-check)
    provider: commerce_customer_user
    context: customer_identity
    organization-form-login:
        enable_csrf: true
        check_path: oro_oauth2_server_frontend_login_check
        login_path: oro_oauth2_server_frontend_login_form
    entry_point: organization_form_login
    logout:
        path: oro_customer_customer_user_security_logout
