services:
    oro_oauth2_server.listener.frontend_routes_listener:
        class: Oro\Bundle\OAuth2ServerBundle\EventListener\FrontendRoutesListener
        tags:
            - { name: kernel.event_listener, event: oro_distribution.route_collection.expose, method: onCollectionAutoload }

    oro_oauth2_server.guest_access.provider.guest_access_urls_provider:
        class: Oro\Bundle\OAuth2ServerBundle\Provider\GuestAccessAllowedUrlsProvider
        calls:
            - [addAllowedUrlPattern, ['^/oauth2-token$']]
        tags: [oro_frontend.guest_access_urls_provider]
