acls:
    oro_oauth2_view:
        type: entity
        permission: VIEW
        class: Oro\Bundle\OAuth2ServerBundle\Entity\Client
        group_name: ""
        bindings: ~

    oro_oauth2_create:
        type: entity
        permission: CREATE
        class: Oro\Bundle\OAuth2ServerBundle\Entity\Client
        group_name: ""
        bindings: ~

    oro_oauth2_edit:
        type: entity
        permission: EDIT
        class: Oro\Bundle\OAuth2ServerBundle\Entity\Client
        group_name: ""
        bindings: ~

    oro_oauth2_delete:
        type: entity
        permission: DELETE
        class: Oro\Bundle\OAuth2ServerBundle\Entity\Client
        group_name: ""
        bindings: ~
