oro_api:
    api_firewalls:
        api_wsse_secured:
            feature_firewall_authenticators: # FeatureDependAuthenticatorChecker
                - Oro\Bundle\OAuth2ServerBundle\Security\Authenticator\OAuth2Authenticator
        wsse_secured:
            feature_firewall_authenticators: # FeatureDependAuthenticatorChecker
                - Oro\Bundle\OAuth2ServerBundle\Security\Authenticator\OAuth2Authenticator
        frontend_api_wsse_secured:
            feature_firewall_authenticators: # FeatureDependAuthenticatorChecker
                - Oro\Bundle\OAuth2ServerBundle\Security\Authenticator\OAuth2Authenticator

oro_security:
    access_control:
        - { path: ^/oauth2-token/login$, roles: PUBLIC_ACCESS }

security:
    password_hashers:
        Oro\Bundle\OAuth2ServerBundle\Entity\Client:
            algorithm: sodium
            migrate_from:
                - sha512
    firewalls:
        oauth2_authorization_login:
            pattern: '^/oauth2-token/login$'
            provider: chain_provider
            context: main
        oauth2_authorization_authenticate:
            pattern: '^/oauth2-token/(authorize|login-check)'
            provider: chain_provider
            context: main
            entry_point: organization_form_login
            organization-form-login:
                enable_csrf: true
                check_path: oro_oauth2_server_login_check
                login_path: oro_oauth2_server_login_form
            logout:
                path: oro_user_security_logout
        oauth2_authorization_server:
            pattern:   '^/oauth2-token$'
            stateless: true
            security:  false

oro_oauth2_server:
    resource_server:
        oauth_firewalls:
            - api_wsse_secured
            - frontend_api_wsse_secured
            - wsse_secured

oro_user:
    login_sources:
        OAuth:
            label: oro.oauth2server.login_source.oauth
            code: 20
        OAuthCode:
            label: oro.oauth2server.login_source.oauth_auth_code
            code: 25
