oro_api:
    api_firewalls:
        api_wsse_secured:
            feature_firewall_listeners:
                - Oro\Bundle\OAuth2ServerBundle\Security\Firewall\OAuth2Listener
        wsse_secured:
            feature_firewall_listeners:
                - Oro\Bundle\OAuth2ServerBundle\Security\Firewall\OAuth2Listener
        frontend_api_wsse_secured:
            feature_firewall_listeners:
                - Oro\Bundle\OAuth2ServerBundle\Security\Firewall\OAuth2Listener

security:
    encoders:
        Oro\Bundle\OAuth2ServerBundle\Entity\Client: sha512
    firewalls:
        oauth2_authorization_login:
            pattern: '^/oauth2-token/login$'
            provider: chain_provider
            anonymous: true
            context: main
        oauth2_authorization_authenticate:
            pattern: '^/oauth2-token/(authorize|login-check)'
            provider: chain_provider
            context: main
            organization-form-login:
                csrf_token_generator: security.csrf.token_manager
                check_path: oro_oauth2_server_login_check
                login_path: oro_oauth2_server_login_form
            logout:
                path: oro_user_security_logout
            anonymous: false
        oauth2_authorization_server:
            pattern:   '^/oauth2-token$'
            stateless: true
            security:  false

oro_oauth2_server:
    resource_server:
        oauth_firewalls:
            - api_wsse_secured
            - frontend_api_wsse_secured
            - wsse_secured

oro_user:
    login_sources:
        OAuth:
            label: oro.oauth2server.login_source.oauth
            code: 20
        OAuthCode:
            label: oro.oauth2server.login_source.oauth_auth_code
            code: 25
