oro_api:
    api_firewalls:
        api_secured:
            feature_firewall_authenticators: # FeatureDependAuthenticatorChecker
                - Oro\Bundle\OAuth2ServerBundle\Security\Authenticator\OAuth2Authenticator
        old_api_secured:
            feature_firewall_authenticators: # FeatureDependAuthenticatorChecker
                - Oro\Bundle\OAuth2ServerBundle\Security\Authenticator\OAuth2Authenticator
        frontend_api_secured:
            feature_firewall_authenticators: # FeatureDependAuthenticatorChecker
                - Oro\Bundle\OAuth2ServerBundle\Security\Authenticator\OAuth2Authenticator

oro_security:
    access_control:
        - { path: ^/oauth2-token/login$, roles: PUBLIC_ACCESS }

security:
    password_hashers:
        Oro\Bundle\OAuth2ServerBundle\Entity\Client:
            algorithm: sodium
            migrate_from:
                - sha512
    firewalls:
        oauth2_authorization_server:
            pattern: '^/oauth2-token$'
            stateless: true
            security: false

oro_oauth2_server:
    resource_server:
        oauth_firewalls:
            - api_secured
            - frontend_api_secured
            - old_api_secured

oro_user:
    login_sources:
        OAuth:
            label: oro.oauth2server.login_source.oauth
            code: 20
        OAuthCode:
            label: oro.oauth2server.login_source.oauth_auth_code
            code: 25
