features:
    web_api:
        routes:
            - oro_oauth2_index
            - oro_oauth2_view
            - oro_oauth2_create
            - oro_oauth2_update
        navigation_items:
            - application_menu.system_tab.users_management.backoffice_oauth_applications
