navigation:
    menu_config:
        items:
            backoffice_oauth_applications:
                label: 'oro.oauth2server.menu.backoffice_oauth_application.label'
                route: 'oro_oauth2_index'
                acl_resource_id: oro_oauth2_view
                position: 60
                extras:
                    routes: ['oro_oauth2_view', 'oro_oauth2_create', 'oro_oauth2_update']
        tree:
            application_menu:
                children:
                    system_tab:
                        children:
                            users_management:
                                children:
                                    backoffice_oauth_applications: ~
    titles:
        oro_oauth2_index: ~
        oro_oauth2_frontend_index: ~
        oro_oauth2_view: '%application.name% - oro.ui.view'
        oro_oauth2_frontend_view: '%application.name% - oro.ui.view'
        oro_oauth2_update: '%application.name% - oro.ui.edit'
        oro_oauth2_frontend_update: '%application.name% - oro.ui.edit'
        oro_oauth2_create: 'oro.ui.create'
        oro_oauth2_frontend_create: 'oro.ui.create'
